### ISSUE TITLE
get specific positions from MSA

### ISSUE THREAD

**Issue by Yogesh1-11** [moshi4/pyMSAviz#10]
hi what if i have to grep and display specific positions only lets say 30 40 50 and 60 from a MSA . is there a direct way rather than writing a new fasta file?
also it will be great if you can add a functionality to upload newick format tree and showing phylogeny on left hand side of header

**Comment by moshi4** [comment]
> hi what if i have to grep and display specific positions only lets say 30 40 50 and 60 from a MSA . is there a direct way rather than writing a new fasta file?

You can easily achieve what you want to do by manipulating the [MultipleSeqAlignment](https://biopython.org/docs/latest/api/Bio.Align.html?highlight=multipleseqalignment#Bio.Align.MultipleSeqAlignment) object in BioPython.

**Code Example**

```python
from pymsaviz import MsaViz, get_msa_testdata

# Plot all msa result
msa_file = get_msa_testdata("HIGD2A.fa")
mv = MsaViz(msa_file, wrap_length=60)
mv.savefig("all_msa.png")

# Plot partial msa result [30,40,50,60]
part_msa = mv.msa[:, 29:30] + mv.msa[:, 39:40] + mv.msa[:, 49:50] + mv.msa[:, 59:60]
part_mv = MsaViz(part_msa)
part_mv.savefig("partial_msa.png")
```

**all_msa.png**

![all_msa](https://github.com/moshi4/pyMSAviz/assets/41852815/6b997b9d-67f1-423b-b95f-b70c8ea055d8)

**partial_msa.png**

![partial_msa](https://github.com/moshi4/pyMSAviz/assets/41852815/bfa99871-98b3-48c5-8833-f4f12d46cb08)

> also it will be great if you can add a functionality to upload newick format tree and showing phylogeny on left hand side of header

Due to technical difficulties, this feature will not be implemented.
